sudo: false
language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - 4
  - 6

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
